# Configuración de puerto y nombre de aplicación
server.port=8080
spring.application.name=GameVault

# Configuración para Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gamevaultdb?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Temporary01!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
cloudinary.cloud_name=dqj5zwfqf
cloudinary.api_key=298584997688162
cloudinary.api_secret=0ZzzMD3a27rlN9rtWKOBtXr8fLs