# Configuración de puerto y nombre de aplicación
server.port=8080
spring.application.name=GameVault

# (Opcional) Usamos H2 en memoria para que Spring Data JPA pueda arrancar feliz
# sin necesidad de tener un servidor MySQL encendido.
spring.datasource.url=jdbc:h2:mem:gamevaultdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update